# Generated by Django 6.0.7 on 2026-07-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='password_last_rotated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='shared_password_hash',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
