# Generated by Django 6.0.7 on 2026-07-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_office_password_last_rotated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='shared_password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
