# Generated by Django 6.0.7 on 2026-07-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_office_shared_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='password_last_rotated',
        ),
        migrations.RemoveField(
            model_name='office',
            name='shared_password_hash',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OFFICE_USER', 'Office User'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'System Administrator')], default='OFFICE_USER', max_length=50),
        ),
    ]
