# Generated by Django 6.0.7 on 2026-07-21 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='direction',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Internal', 'Internal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
