# Generated by Django 6.0.7 on 2026-08-01 21:58

import apps.correspondence.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0002_correspondence_document_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), apps.correspondence.models.validate_attachment_size]),
        ),
    ]
