# Generated by Django 6.0.7 on 2026-08-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0003_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencemovement',
            name='new_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='correspondencemovement',
            name='previous_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='correspondencemovement',
            name='action_type',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Forwarded', 'Forwarded'), ('Stage Updated', 'Stage Updated'), ('Completed', 'Completed'), ('Note Added', 'Note Added'), ('Attachment Uploaded', 'Attachment Uploaded')], max_length=25),
        ),
    ]
