# Generated by Django 6.0.7 on 2026-08-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0004_correspondencemovement_new_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencemovement',
            name='action_type',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Forwarded', 'Forwarded'), ('Stage Updated', 'Stage Updated'), ('Completed', 'Completed'), ('Note Added', 'Note Added'), ('Attachment Uploaded', 'Attachment Uploaded'), ('Filed', 'Filed')], max_length=25),
        ),
    ]
