# Generated by Django 6.0.7 on 2026-07-17 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('correspondence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('Registered', 'Registered'), ('Forwarded', 'Forwarded'), ('Stage Updated', 'Stage Updated'), ('Completed', 'Completed'), ('Security', 'Security')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('correspondence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='correspondence.correspondence')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.office')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action_type'], name='audit_audit_action__dd3a3c_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx')],
            },
        ),
    ]
