# Generated by Django 6.0.7 on 2026-08-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Forwarded', 'Forwarded'), ('Stage Updated', 'Stage Updated'), ('Completed', 'Completed'), ('Security', 'Security'), ('Report Generated', 'Report Generated'), ('Report Viewed', 'Report Viewed')], max_length=20),
        ),
    ]
