# Generated by Django 6.0.7 on 2026-07-19 00:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('correspondence_type', models.CharField(max_length=30)),
                ('count_registered', models.PositiveIntegerField(default=0)),
                ('count_completed', models.PositiveIntegerField(default=0)),
                ('count_overdue', models.PositiveIntegerField(default=0)),
                ('avg_turnaround_hours', models.FloatField(blank=True, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='accounts.office')),
            ],
            options={
                'indexes': [models.Index(fields=['office', 'date'], name='reports_rep_office__7cbdff_idx')],
                'unique_together': {('office', 'date', 'correspondence_type')},
            },
        ),
    ]
