# Generated by Django 6.0.7 on 2026-08-09 02:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_office_password_last_rotated_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_reference', models.CharField(editable=False, max_length=100, unique=True)),
                ('report_type', models.CharField(choices=[('OFFICE_PERFORMANCE', 'Office Performance'), ('OVERDUE', 'Overdue Documents'), ('PENDING_AGEING', 'Pending and Ageing'), ('STAFF_CONTRIBUTION', 'Staff Contribution')], max_length=30)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('custom', 'Custom')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('snapshot', models.JSONField()),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formal_reports', to='accounts.office')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
