# Generated by Django 6.0.7 on 2026-08-09 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_office_password_last_rotated_and_more'),
        ('reports', '0002_formalreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='formalreport',
            index=models.Index(fields=['office', 'report_type', 'period_start', 'period_end'], name='reports_for_office__7d21a9_idx'),
        ),
    ]
